### PR TITLE
Add inventory debug job, move job filter and form entry mixin here for reused, enhance secretgroups

### PR DESCRIPTION
**Pull request by jeffkala**
1. Add a debug inventory job that will be hidden by default. Will help folks debug GC and other plugins that eventually use this shim layer.
2. Moving job_filter helper and job input form mixin into here for reuse by other apps, eventually GCs use of those will be imported from this plugin and removed from native GC plugin
3. Enhanced the nautobot secrets credentials class to include a in memory cache to avoid the constant re-querying of secrets providers for the same secrets information over and over.  This should help specifically with issues seen with Delinea secrets provider where timeouts, rate-limiting etc. cause slowness and inventory population/creation issues.

### CODE REVIEW

**Review by jvanderaa — APPROVED** [review]

**Comment by jeffkala** [comment]
Did some baseline testing with HashiCorp vault as the secrets provider on 1000 devices.  The nornir inventory build before this change took 0 minutes, 41.93 seconds.  With the introduction of the in memory cache it took 0 minutes, 18.76 seconds.

**Comment by jeffkala** [comment]
Putting in draft while I test lru_cache instead, as well as figuring out why certain data in the debug output isn't getting sanitized.
For example connection options "secrets" dictionary key.

**Comment by jeffkala** [comment]
opened https://github.com/nautobot/nautobot/pull/4994/files to try and enhance default sanitizer.

**Comment by jeffkala** [comment]
Looking at this more, looks like this works except for the cases where templating is used in the secrets definition.  When that is the case the cache is just going to use incorrect values. Investigating additional ways to handle this.

**Comment by jeffkala** [comment]
This should be working now.

**Comment by jeffkala** [comment]
With newest caching solutions for 1000 devices using secrets groups:
- current pypi release: `0 minutes, 40.57 seconds`
- this PR: `0 minutes, 29.19 seconds`

This is using hashicorp vault (a local instance which has essentially zero latency), these numbers should be even greater for solutions where the secrets provider itself is not physically located in the same local broadcast domain as nautobot.

**Comment by jeffkala** [comment]
Would love to do more testing before this gets out of draft stage. From my initial testing everything works well, even when using secrets templating functionality.

**Comment by jeffkala** [comment]
closing this, the job and debug job is not needed.  Going to do a new PR with just the credentials cach solution.

**Pull request closed without merging**
