### PR TITLE
LTM: Deprecates Python 3.7

### PR DESCRIPTION
**Pull request by Kircheneer**
The tight pin on `importlib-metadata` is causing some issues. Since its only necessary for the EOL'd Python 3.7, this PR deprecates Python 3.7 and removes the dependency.

### CODE REVIEW

**Comment by jeffkala** [comment]
@Kircheneer can you also update pyproject.toml for `black` section: target-version = ['py37'] is still showing.

**Comment by itdependsnetworks** [comment]
Do you mind doing this on nautobot core? Makes sense to defer that decision to them and we should align with their decision.

**Comment by glennmatthews** [comment]
Core already dropped python 3.8 support and removed importlib-metadata - https://github.com/nautobot/nautobot/pull/3554 and https://github.com/nautobot/nautobot/pull/4118

**Comment by jeffkala** [comment]
Will update this PR, also need to rework the CI pipeline files.

**Pull request merged**
